# Form implementation generated from reading ui file 'C:\Users\PC\Documents\GitHub\Customer-Management-project\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 651)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 50, 471, 71))
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 120, 551, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.name_label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.name_label.setStyleSheet("border: 1px solid rgb(200, 200, 200);\n"
"font-family: \'Arial\';  \n"
"font-size: 16px;      \n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(254, 255, 230)")
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 1, 0, 1, 1)
        self.id_input = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.id_input.setFont(font)
        self.id_input.setStyleSheet("border: 1px solid rgb(200, 200, 200);\n"
"font-family: \'Arial\';  \n"
"font-size: 16px;      \n"
"color: rgb(255, 0, 0);\n"
"background-color:rgb(254, 255, 230)")
        self.id_input.setObjectName("id_input")
        self.gridLayout.addWidget(self.id_input, 0, 1, 1, 1)
        self.email_label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.email_label.setStyleSheet("border: 1px solid rgb(200, 200, 200);\n"
"font-family: \'Arial\';  \n"
"font-size: 16px;      \n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(254, 255, 230)")
        self.email_label.setObjectName("email_label")
        self.gridLayout.addWidget(self.email_label, 2, 0, 1, 1)
        self.id_label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.id_label.setStyleSheet("border: 1px solid rgb(200, 200, 200);\n"
"font-family: \'Arial\';  \n"
"font-size: 16px;      \n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(254, 255, 230)")
        self.id_label.setObjectName("id_label")
        self.gridLayout.addWidget(self.id_label, 0, 0, 1, 1)
        self.name_input = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.name_input.setFont(font)
        self.name_input.setStyleSheet("border: 1px solid rgb(200, 200, 200);\n"
"font-family: \'Arial\';  \n"
"font-size: 16px;      \n"
"color: rgb(255, 0, 0);\n"
"background-color:rgb(254, 255, 230)")
        self.name_input.setObjectName("name_input")
        self.gridLayout.addWidget(self.name_input, 1, 1, 1, 1)
        self.email_input = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.email_input.setFont(font)
        self.email_input.setStyleSheet("border: 1px solid rgb(200, 200, 200);\n"
"font-family: \'Arial\';  \n"
"font-size: 16px;      \n"
"color: rgb(255, 0, 0);\n"
"background-color:rgb(254, 255, 230)")
        self.email_input.setObjectName("email_input")
        self.gridLayout.addWidget(self.email_input, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.edit_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.edit_button.setFont(font)
        self.edit_button.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.reset_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.reset_button.setFont(font)
        self.reset_button.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.customer_list = QtWidgets.QListWidget(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.customer_list.setFont(font)
        self.customer_list.setStyleSheet("border: 1px solid rgb(200, 200, 200);\n"
"font-family: \'Arial\';  \n"
"font-size: 16px;      \n"
"color: rgb(255, 0, 0);\n"
"background-color:rgb(230, 255, 248)")
        self.customer_list.setObjectName("customer_list")
        self.verticalLayout_2.addWidget(self.customer_list)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#005500;\">CUSTOMER MANAGEMENT</span></p></body></html>"))
        self.name_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Full Name:       </span></p></body></html>"))
        self.email_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Email:</span></p></body></html>"))
        self.id_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Customer Code:                            </span></p></body></html>"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.edit_button.setText(_translate("MainWindow", "Edit"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
